scrape_configs:
  - job_name: 'sophos_ssh_exporter'
    scrape_interval: 60s
    scrape_timeout: 45s       # QUAN TRỌNG: Phải tăng lên vì SSH cần thời gian
    metrics_path: /scrape
    params:
      module: [default]       # Tên module được khai báo trong config.yml
    static_configs:
      - targets:
        - 10.121.1.250        # Danh sách IP thiết bị thật được khai báo ở đây
        - 10.121.1.251
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9200  # Địa chỉ và port của tool sophos_ssh_exporter đang chạy